#!/bin/zsh

# go/Lyftenv
PATH=$PATH:/Users/urielcoria/.lyftkube-bin
export PATH=$HOME/src/lyftvenv/bin:$PATH 
eval "$(/opt/homebrew/bin/aactivator init)"
# This secret line of code will help us 
# save a fuck ton of cpu sorry employer wasnt me 
#         .-"""-.
#        /       \
#        \       /
# .-"""-.-`.-.-.<  _
#/      _,-\ ()()_/:)
#\     / ,  `     `|
# '-..-| \-.,___,  /
#       \ `-.__/  /
#        `-.__.-'`
alias killCode24="sudo launchctl unload /Library/LaunchDaemons/com.code42.service.plist"

# Lyft
alias runlyft="aws-okta exec zimride-client-team-access-readonly -- runlyft"
alias lyftkube="aws-okta exec zimride-sudo-developer -- lyftkube"
alias precommit="pre-commit run --all-files"

if [[ -f "/opt/homebrew/Library/Taps/lyft/homebrew-localdevtools/scripts/shell_rc.sh" ]]; then
    source "/opt/homebrew/Library/Taps/lyft/homebrew-localdevtools/scripts/shell_rc.sh"
fi
