#!/bin/zsh

# go/Lyftenv
# Consolidated PATH exports to eliminate pollution - single optimized export
export PATH="$HOME/src/lyftvenv/bin:$PATH:/Users/urielcoria/.lyftkube-bin:$HOME/.rd/bin"
eval "$(/opt/homebrew/bin/aactivator init)"
eval "$(/Users/urielcoria/src/idl/idldev-tool/bin/idldev init -)"
# This secret line of code will help us 
# save a fuck ton of cpu sorry employer wasnt me 
#         .-"""-.
#        /       \
#        \       /
# .-"""-.-`.-.-.<  _
#/      _,-\ ()()_/:)
#\     / ,  `     `|
# '-..-| \-.,___,  /
#       \ `-.__/  /
#        `-.__.-'`
alias killCode24="sudo launchctl unload /Library/LaunchDaemons/com.code42.service.plist"
alias runlyft="aws-okta exec zimride-client-team-access-readonly -- runlyft" 
alias lyftkube="lyftkube"
alias precommit="pre-commit run --all-files"
alias lyftme="runlyft -b master -d 'iPhone 15 Pro'"
alias ios-generate="./ios generate Lyft, DriverApp, Lyft-UITests, Driver-UITests, PassengerAppUITestHelpers, DriverAppUITestHelpers, App-UITests,"
alias ios-lint="./ios lint"
alias ios-fix="./ios fix"
alias dev-ios="cd ~/src/Lyft-iOS/"
alias dev-andr="cd ~/src/instant-android/"
### lyft_localdevtools_shell_rc start (consolidated - was duplicated)
### DO NOT REMOVE: automatically installed as part of Lyft local dev tool setup
if [[ -f "/opt/homebrew/Library/Taps/lyft/homebrew-localdevtools/scripts/shell_rc.sh" ]]; then
    source "/opt/homebrew/Library/Taps/lyft/homebrew-localdevtools/scripts/shell_rc.sh"
fi
### lyft_localdevtools_shell_rc end
# PATH already includes /opt/homebrew/bin from localdevtools - removed duplicate

### lyft_rd_shell_rc start
### DO NOT REMOVE: automatically installed as part of Rancher Desktop setup
if [[ -f /Users/urielcoria/.rd/shell_rc.sh ]]; then
  source /Users/urielcoria/.rd/shell_rc.sh
fi
### lyft_rd_shell_rc end

### DO NOT REMOVE: automatically installed as part of Lyft local dev tool setup
eval "$(fnm env --use-on-cd --version-file-strategy=recursive)"

# Lyft Android/Java Development Environment (moved from .zshrc)
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home
export ANDROID_HOME=/Users/urielcoria/.androidbin/lyft-android-sdk/android-sdk-4333796-unarchived/

## PYENV 
# Final consolidated PATH export with all Lyft tools
export PATH="$PATH:$HOME/.pyenv/bin:$JAVA_HOME/bin"

# Initialize pyenv
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

# Initialize pyenv-virtualenv
eval "$(pyenv virtualenv-init -)"

#eval "$(aactivator init)"
export APPLICATION_ENV="production"

uiautomator () {
	export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home
	export ANDROID_HOME=/Users/urielcoria/Library/Android/sdk
	export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools:$ANDROID_HOME/tools
	/Users/urielcoria/Library/Android/sdk/tools/bin/uiautomatorviewer
}
